use_frameworks!

target 'ServiceNowIncidentCreation_Example' do
  pod 'ServiceNowIncidentCreation', :path => '../'

  target 'ServiceNowIncidentCreation_Tests' do
    inherit! :search_paths

    
  end
end
